runtime: nodejs16

handlers:
  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico

env_variables:
   DB_USER: phantomNG
   DB_PASS: phantom_123
   DB_NAME: db_natgas_phantom
   INSTANCE_CONNECTION_NAME : phantom-itesm:us-west2:db-natgas-phantom
   GCLOUD_STORAGE_BUCKET: phantom-itesm.appspot.com